AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template
Globals:
  Function:
    Timeout: 30
Resources:
  lamone:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lamone
      CodeUri: lamone/
      Runtime: nodejs14.x
      Handler: app.lambdaHandler
  lamtwo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lamtwo
      CodeUri: lamtwo/
      Runtime: nodejs14.x
      Handler: app.lambdaHandler
