AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template
Globals:
  Function:
    Timeout: 30
Resources:
  lambdas:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambdas
      CodeUri: lambdas/
      Runtime: nodejs14.x
      Environment:
        Variables: {}
      Policies:
        - AWSLambdaDynamoDBExecutionRole
      Handler: app.lambdaHandler
